# Change these first
owner: zer-far # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website - ampis.org
    url: https://ampis.org
  - name: Allium - tor.ampis.org
    url: https://tor.ampis.org
  - name: Chat - chat.ampis.org
    url: https://chat.ampis.org
  - name: Calendar - calendar.ampis.org
    url: https://calendar.ampis.org
  - name: Pastebin - pastebin.ampis.org
    url: https://pastebin.ampis.org

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.ampis.org
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.ampis.org
  introTitle: "***ampis.org** status page."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
